version: '3'

services:
  api-server:
    build:
      context: .
    image: api-server
    restart: unless-stopped
    depends_on:
      - mongo_service
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - '3000:3000'

networks:
  app-network:
    driver: bridge
