version: '3'
services:
  npuserserver:
    build:
      context: ../server
      dockerfile: Dockerfile
    image: npuserserver
    hostname: npuserserver
    environment:
      - API_HOST
      - API_PORT
      - AUTH_TOKEN_SECRET
      - CLIENT_HOST
      - CLIENT_PORT
      - NODE_ENV
      - PROXY_PASS_HOST
      - SCHEME
      - SERVER_PORT
      - START_ARG
    ports:
      - 27001:27001
    restart: unless-stopped
    volumes:
      - ../logs/api:/logs
    entrypoint:
      - npm
      - run
      - ${START_ARG}
    networks:
      - default
      - npuser-network

networks:
  npuser-network:
    driver: bridge
    name: npuser-network
