version: '3'
services:
  npuserserver:
    build:
      context: ../server
      dockerfile: Dockerfile
    image: npuserserver
    hostname: npuserserver
    environment:
      - API_HOST
      - API_PORT
      - AUTH_TOKEN_SECRET
      - CLIENT_HOST
      - CLIENT_PORT
      - NODE_ENV
      - PROXY_PASS_HOST
      - SCHEME
      - SERVER_PORT
      - START_ARG
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: unless-stopped
    volumes:
      - ../logs/api:/logs
    entrypoint:
      - npm
      - run
      - ${START_ARG}
    networks:
      - default
      - npuser-network
    healthcheck:
      test: curl -f http://npuserserver:${SERVER_PORT} >/dev/null 2>&1
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  npuser-network:
    driver: bridge
    name: npuser-network
