version: '3'
services:
  caddy:
    build:
      context: ../caddy
      dockerfile: Dockerfile
      args:
        - NODE_ENV
        - PROXY_PASS_HOST
        - SERVER_PORT
        - DOMAIN
        - CURRENT_UID
    # user: ${CURRENT_UID}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../site:/var/www
      - ../log:/var/log
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile
      - ../caddy/caddy_data:/data
      - ../caddy/caddy_config:/config