version: '3'
services:
  caddy:
    build:
      context: ../caddy
      dockerfile: Dockerfile
      args:
        - NODE_ENV
        - PROXY_PASS_HOST
        - SERVER_PORT
        - DOMAIN
        - CURRENT_UID
    # user: ${CURRENT_UID}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../client/dist:/var/www
      - ../logs/site:/var/log
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile
      - ../caddy/caddy_data:/data
      - ../caddy/caddy_config:/config

  api-server:
    build:
      context: ../server
      dockerfile: Dockerfile
    image: api-server
    restart: unless-stopped
    depends_on:
      - mongo_service
    volumes:
      - ../logs/api:/logs
    ports:
      - '3000:3000'

  mongo_service:
    image: mongo
    restart: always
    volumes:
      - ./db_data:/data/db
    ports:
      - "27017:27017"