version: '3'

services:
  mongo_service:
    image: mongo
    container_name: mongo-dev
    restart: always
    networks:
      - app-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge
